apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-http-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-http-staging
    spec:
      containers:
      - name: helloworld
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
