apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    tier: app
    app: multi-container
  namespace: multi-container
spec:
  containers:
    - name: server
      image: "slashdeploy/microservice-example:server-v1"
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    tier: app
spec:
  selector:
    tier: app
    app: multi-container
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP