apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: pods-and-services
spec:
  selector:
    app: pods-and-services
  ports:
    - port: 80
      targetPort: 80
  type: NodePort

