apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: deploy
    tier: data
  namespace: deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy
      tier: data
  template:
    metadata:
      name: redis
      labels:
        app: deploy
        tier: data
    spec:  
      containers:
        - name: redis
          image: "redis:latest"
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"