apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: deploy
    tier: data
  namespace: deploy
spec:
  capacity:
    storage: 128M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/example