apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    app: deploy
    tier: data
  namespace: deploy
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem    
  resources:
    requests:
      storage: 128M
  # selector:
  #   matchLabels:
  #     app: deploy
  #     tier: data      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: deploy
    tier: data
  namespace: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy
      tier: data
  template:
    metadata:
      name: redis
      labels:
        app: deploy
        tier: data
    spec:  
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
        - name: logs
          hostPath: 
            path: /var/log/pods
      containers:
        - name: redis
          image: "redis:latest"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /logs
              name: logs
              subPath: $(POD_NAME)
